CREATE TABLE `acctbal` (
  `acctBalID` int(11) NOT NULL AUTO_INCREMENT,
  `cli_no` varchar(11) DEFAULT NULL,
  `cli_name` varchar(50) DEFAULT NULL,
  `rep_no` int(11) DEFAULT NULL,
  `source` varchar(3) DEFAULT NULL,
  `dst_amt` decimal(17,2) DEFAULT NULL,
  `net_amt` decimal(12,2) DEFAULT NULL,
  `bet_amt` decimal(12,2) DEFAULT NULL,
  `branch_no` varchar(5) DEFAULT NULL,
  `rep_name` varchar(30) DEFAULT NULL,
  `soc_sec` varchar(11) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`acctBalID`)
);

CREATE TABLE `acctpos` (
  `acctPosID` int(11) NOT NULL AUTO_INCREMENT,
  `source` varchar(3) DEFAULT NULL,
  `rep_no` int(11) DEFAULT NULL,
  `invest` varchar(35) DEFAULT NULL,
  `co_no` smallint(6) DEFAULT NULL,
  `cusip_no` varchar(9) DEFAULT NULL,
  `company` varchar(35) DEFAULT NULL,
  `inv_type` tinyint(4) DEFAULT NULL,
  `inv_no` int(11) DEFAULT NULL,
  `date_placed` datetime DEFAULT NULL,
  `date_rec` datetime DEFAULT NULL,
  `activ_date` datetime DEFAULT NULL,
  `buy_sell` char(1) DEFAULT NULL,
  `units` decimal(17,4) DEFAULT NULL,
  `price` decimal(14,6) DEFAULT NULL,
  `net_amt` decimal(17,2) DEFAULT NULL,
  `d_amt` decimal(17,2) DEFAULT NULL,
  `f_amt` decimal(17,2) DEFAULT NULL,
  `cli_no` varchar(11) DEFAULT NULL,
  `soc_sec` varchar(11) DEFAULT NULL,
  `addr` varchar(30) DEFAULT NULL,
  `city` varchar(20) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zip` varchar(10) DEFAULT NULL,
  `cli_name` varchar(40) DEFAULT NULL,
  `fname` varchar(20) DEFAULT NULL,
  `lname` varchar(20) DEFAULT NULL,
  `middle` char(1) DEFAULT NULL,
  `branch_no` varchar(5) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`acctPosID`)
);

CREATE TABLE `branches` (
  `branchID` int(11) NOT NULL AUTO_INCREMENT,
  `branch_no` varchar(5) DEFAULT NULL,
  `branch_name` varchar(50) DEFAULT NULL,
  `rep_no` int(11) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime NOT NULL,
  PRIMARY KEY (`branchID`)
);

CREATE TABLE `clearing` (
  `clearID` int(11) NOT NULL AUTO_INCREMENT,
  `cli_no` varchar(11) DEFAULT NULL,
  `clearing` varchar(20) DEFAULT NULL,
  `co_no` int(11) DEFAULT NULL,
  `company` varchar(35) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`clearID`)
);

CREATE TABLE `clients` (
  `clientsID` int(11) NOT NULL AUTO_INCREMENT,
  `cli_no` varchar(11) DEFAULT NULL,
  `dateCreated` datetime DEFAULT NULL,
  `cli_name` varchar(40) DEFAULT NULL,
  `address` varchar(62) DEFAULT NULL,
  `phone` varchar(13) DEFAULT NULL,
  `rep_no` int(11) DEFAULT NULL,
  `branch_no` int(11) DEFAULT NULL,
  `birth_date` datetime DEFAULT NULL,
  `last_trade` datetime DEFAULT NULL,
  `addr` varchar(30) DEFAULT NULL,
  `city` varchar(20) DEFAULT NULL,
  `state` varchar(2) DEFAULT NULL,
  `zip` varchar(50) DEFAULT NULL,
  `lname` varchar(25) DEFAULT NULL,
  `fname` varchar(15) DEFAULT NULL,
  `middle` char(1) DEFAULT NULL,
  `soc_sec` varchar(11) DEFAULT NULL,
  `employer` varchar(40) DEFAULT NULL,
  `empaddr` varchar(40) DEFAULT NULL,
  `nocontact` tinyint(1) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  `addr2` varchar(30) DEFAULT NULL,
  `longname` varchar(200) DEFAULT NULL,
  `acct_type` varchar(25) DEFAULT NULL,
  `inact_date` datetime DEFAULT NULL,
  `nac_date` datetime DEFAULT NULL,
  `jtsoc_sec` varchar(11) DEFAULT NULL,
  `jtname` varchar(45) DEFAULT NULL,
  `jtdob` datetime DEFAULT NULL,
  `closed` datetime DEFAULT NULL,
  `rap` datetime DEFAULT NULL,
  `cru_date` datetime DEFAULT NULL,
  `m_addr` varchar(30) DEFAULT NULL,
  `m_addr2` varchar(30) DEFAULT NULL,
  `m_city` varchar(30) DEFAULT NULL,
  `m_state` varchar(2) DEFAULT NULL,
  `m_zip` varchar(10) DEFAULT NULL,
  `open_date` datetime DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL
  PRIMARY KEY (`clientsID`)
);

CREATE TABLE `clipol` (
  `clipolID` int(11) NOT NULL AUTO_INCREMENT,
  `cli_no` varchar(11) DEFAULT NULL,
  `policy` varchar(20) DEFAULT NULL,
  `co_no` int(11) DEFAULT NULL,
  `inv_no` int(11) DEFAULT NULL,
  `inv_type` int(11) DEFAULT NULL,
  `rep_no` int(11) DEFAULT NULL,
  `ins_type` int(11) DEFAULT NULL,
  `det_type` int(11) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `cash` decimal(12,2) DEFAULT NULL,
  `benefit` decimal(12,2) DEFAULT NULL,
  `premium` decimal(12,2) DEFAULT NULL,
  `cashtype` int(11) DEFAULT NULL,
  `notissued` int(11) DEFAULT NULL,
  `invest` varchar(50) DEFAULT NULL,
  `incep_date` datetime DEFAULT NULL,
  `company` varchar(50) DEFAULT NULL,
  `customerid` int(11) DEFAULT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`clipolID`)
);

CREATE TABLE `clisuit` (
  `clisuitID` int(11) NOT NULL AUTO_INCREMENT,
  `cli_no` varchar(11) DEFAULT NULL,
  `income` int(11) DEFAULT NULL,
  `net_worth` int(11) DEFAULT NULL,
  `taxbracket` int(11) DEFAULT NULL,
  `liquid_net` int(11) DEFAULT NULL,
  `risktol` int(11) DEFAULT NULL,
  `objectives` int(11) DEFAULT NULL,
  `marital` int(11) DEFAULT NULL,
  `obtained` int(11) DEFAULT NULL,
  `acctsour` int(11) DEFAULT NULL,
  `sourfund` int(11) DEFAULT NULL,
  `invknow` int(11) DEFAULT NULL,
  `know_stk` int(11) DEFAULT NULL,
  `know_mf` int(11) DEFAULT NULL,
  `know_bnd` int(11) DEFAULT NULL,
  `know_va` int(11) DEFAULT NULL,
  `know_opt` int(11) DEFAULT NULL,
  `know_lp` int(11) DEFAULT NULL,
  `user_s` varchar(3) DEFAULT NULL,
  `expyr_mut` int(11) DEFAULT NULL,
  `expyr_stk` int(11) DEFAULT NULL,
  `expyr_bnd` int(11) DEFAULT NULL,
  `expyr_opt` int(11) DEFAULT NULL,
  `expyr_spf` int(11) DEFAULT NULL,
  `expyr_ann` int(11) DEFAULT NULL,
  `expyr_alt` int(11) DEFAULT NULL,
  `expyr_mgn` int(11) DEFAULT NULL,
  `txpyr_mut` int(11) DEFAULT NULL,
  `txpyr_stk` int(11) DEFAULT NULL,
  `txpyr_bnd` int(11) DEFAULT NULL,
  `txpyr_opt` int(11) DEFAULT NULL,
  `txpyr_spf` int(11) DEFAULT NULL,
  `txpyr_ann` int(11) DEFAULT NULL,
  `txpyr_alt` int(11) DEFAULT NULL,
  `txpyr_mgn` int(11) DEFAULT NULL,
  `expann` int(11) DEFAULT NULL,
  `expspec` int(11) DEFAULT NULL,
  `expspectf` int(11) DEFAULT NULL,
  `liq_need` int(11) DEFAULT NULL,
  `decmaker` varchar(10) DEFAULT NULL,
  `port_part` int(11) DEFAULT NULL,
  `acct_use` int(11) DEFAULT NULL,
  `acct_useo` varchar(25) DEFAULT NULL,
  `timehor` int(11) DEFAULT NULL,
  `signdate` datetime DEFAULT NULL,
  `signer` varchar(40) DEFAULT NULL,
  `newfld` varchar(10) DEFAULT NULL,
  `clirecno` int(11) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `edited` datetime DEFAULT NULL,
  `creator` varchar(3) DEFAULT NULL,
  `editor` varchar(3) DEFAULT NULL,
  `assets` int(11) DEFAULT NULL,
  `ann_exp` int(11) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`clisuitID`)
);

CREATE TABLE `company` (
  `companyID` int(11) NOT NULL AUTO_INCREMENT,
  `company` varchar(35) NOT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`companyID`)
);

CREATE TABLE `customers` (
  `customerID` int(11) NOT NULL AUTO_INCREMENT,
  `customerName` varchar(200) NOT NULL,
  `webpath` varchar(50) NOT NULL,
  `lastImportDate` datetime DEFAULT NULL,
  `odbcdsn` varchar(50) DEFAULT NULL,
  `fieldList_acctPos` varchar(1000) DEFAULT NULL,
  `fieldList_clients` varchar(1000) DEFAULT NULL,
  `fieldList_permrep` varchar(1000) DEFAULT NULL,
  `fieldList_trades` varchar(1000) DEFAULT NULL,
  `fieldList_branches` varchar(1000) DEFAULT NULL,
  `fieldList_acctBal` varchar(1000) DEFAULT NULL,
  `fieldList_clearing` varchar(1000) DEFAULT NULL,
  `fileProcessed_acctPos` tinyint(1) DEFAULT NULL,
  `fileProcessed_clients` tinyint(1) DEFAULT NULL,
  `fileProcessed_permrep` tinyint(1) DEFAULT NULL,
  `fileProcessed_trades` tinyint(1) DEFAULT NULL,
  `fileProcessed_branches` tinyint(1) DEFAULT NULL,
  `fileProcessed_acctBal` tinyint(1) DEFAULT NULL,
  `fileProcessed_clearing` tinyint(1) DEFAULT NULL,
  `logoFile` varchar(100) DEFAULT NULL,
  `homeURL` varchar(200) DEFAULT NULL,
  `accessPhone` varchar(50) DEFAULT NULL,
  `testfield` tinyint(1) DEFAULT NULL,
  `fieldList_clipol` varchar(1000) DEFAULT NULL,
  `fieldList_clisuit` varchar(1000) DEFAULT NULL,
  `fileProcessed_clipol` tinyint(1) DEFAULT NULL,
  `fileProcessed_clisuit` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`customerID`)
);

CREATE TABLE `importlog` (
  `importID` int(11) NOT NULL AUTO_INCREMENT,
  `customerID` int(11) NOT NULL,
  `success` tinyint(1) NOT NULL,
  `message` varchar(500) DEFAULT NULL,
  `logDateTime` datetime NOT NULL,
  PRIMARY KEY (`importID`)
);

CREATE TABLE `invest` (
  `investID` int(11) NOT NULL AUTO_INCREMENT,
  `invest` varchar(35) NOT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`investID`)
);

CREATE TABLE `permrep` (
  `permRepID` int(11) NOT NULL AUTO_INCREMENT,
  `rep_no` int(11) DEFAULT NULL,
  `clear_no` varchar(5) DEFAULT NULL,
  `fname` varchar(20) DEFAULT NULL,
  `lname` varchar(20) DEFAULT NULL,
  `middle` varchar(1) DEFAULT NULL,
  `suffix` varchar(3) DEFAULT NULL,
  `h_addr` varchar(30) DEFAULT NULL,
  `h_city` varchar(24) DEFAULT NULL,
  `h_state` varchar(2) DEFAULT NULL,
  `h_zip` varchar(50) DEFAULT NULL,
  `m_addr` varchar(30) DEFAULT NULL,
  `m_addr2` varchar(30) DEFAULT NULL,
  `m_city` varchar(24) DEFAULT NULL,
  `m_state` varchar(2) DEFAULT NULL,
  `m_zip` varchar(50) DEFAULT NULL,
  `w_phone` varchar(13) DEFAULT NULL,
  `h_phone` varchar(13) DEFAULT NULL,
  `fax` varchar(13) DEFAULT NULL,
  `soc_sec` varchar(11) DEFAULT NULL,
  `taxid` varchar(50) DEFAULT NULL,
  `emp_date` datetime DEFAULT NULL,
  `crd_no` varchar(7) DEFAULT NULL,
  `term_date` datetime DEFAULT NULL,
  `lp_states` char(54) DEFAULT NULL,
  `mut_states` char(54) DEFAULT NULL,
  `sec_states` char(54) DEFAULT NULL,
  `va_states` char(54) DEFAULT NULL,
  `fa_states` char(54) DEFAULT NULL,
  `l_states` char(54) DEFAULT NULL,
  `ria_states` char(54) DEFAULT NULL,
  `branch` varchar(20) DEFAULT NULL,
  `branch_no` varchar(5) DEFAULT NULL,
  `override` int(11) DEFAULT NULL,
  `over_rate` decimal(5,3) DEFAULT NULL,
  `override2` int(11) DEFAULT NULL,
  `over2_rate` decimal(5,3) DEFAULT NULL,
  `override3` int(11) DEFAULT NULL,
  `over3_rate` decimal(5,3) DEFAULT NULL,
  `dob` datetime DEFAULT NULL,
  `paytype` tinyint(4) DEFAULT NULL,
  `notes` text,
  `equi_acct` varchar(9) DEFAULT NULL,
  `commbasis` tinyint(4) DEFAULT NULL,
  `frn_dom` tinyint(4) DEFAULT NULL,
  `seccalc` tinyint(4) DEFAULT NULL,
  `branch1` varchar(5) DEFAULT NULL,
  `branch2` varchar(5) DEFAULT NULL,
  `branch3` varchar(5) DEFAULT NULL,
  `pay_tot` decimal(10,2) DEFAULT NULL,
  `gross_tot` decimal(10,2) DEFAULT NULL,
  `sec_calc` tinyint(4) DEFAULT NULL,
  `defer_rate` decimal(5,3) DEFAULT NULL,
  `defer_amt` decimal(8,2) DEFAULT NULL,
  `spl_rep` int(11) DEFAULT NULL,
  `spl_rate` decimal(5,3) DEFAULT NULL,
  `spl_rep2` int(11) DEFAULT NULL,
  `spl2_rate` decimal(5,3) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `webpswd` varchar(50) DEFAULT NULL,
  `insur` tinyint(4) DEFAULT NULL,
  `ria` tinyint(4) DEFAULT NULL,
  `cfp` tinyint(4) DEFAULT NULL,
  `cfa` tinyint(4) DEFAULT NULL,
  `clu` tinyint(4) DEFAULT NULL,
  `cpa` tinyint(4) DEFAULT NULL,
  `chfa` tinyint(4) DEFAULT NULL,
  `sal_no` varchar(20) DEFAULT NULL,
  `username` varchar(50) DEFAULT NULL,
  `accessLevel` tinyint(4) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  `bnd_states` char(54) DEFAULT NULL,
  `opt_states` char(54) DEFAULT NULL,
  `rep_link` varchar(10) DEFAULT NULL,
  `osjmgr` int(11) DEFAULT NULL,
  `osjmgr2` int(11) DEFAULT NULL,
  PRIMARY KEY (`permRepID`)
);

CREATE TABLE `prodtype` (
  `prodtypeID` int(11) NOT NULL AUTO_INCREMENT,
  `product` varchar(35) NOT NULL,
  `abbrev` varchar(3) DEFAULT NULL,
  `inv_type` smallint(6) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`prodtypeID`)
);

CREATE TABLE `states` (
  `stateid` int(11) NOT NULL AUTO_INCREMENT,
  `statename` varchar(30) NOT NULL,
  `stateabbrev` varchar(3) NOT NULL,
  `bitIndex` int(11) DEFAULT NULL,
  PRIMARY KEY (`stateid`)
);

CREATE TABLE IF NOT EXISTS trades(
	tradesID INT AUTO_INCREMENT NOT NULL,
	trade_no INT NOT NULL,
	dateTrade DATETIME NOT NULL,
	set_date DATETIME NULL,
	cli_no VARCHAR(11) NULL,
	cli_name VARCHAR(40) NULL,
	invest VARCHAR(50) NULL,
	inv_no INT NULL,
	net_amt DECIMAL(13, 2) NULL,
	comm_exp DECIMAL(9, 2) NULL,
	comm_rec DECIMAL(9, 2) NULL,
	charge DECIMAL(8, 2) NULL,
	date_rec DATETIME NULL,
	pay_date DATETIME NULL,
	rep_comm DECIMAL(10, 2) NULL,
	rep_no INT NULL,
	sal_no VARCHAR(20) NULL,
	branch_mgr VARCHAR(40) NULL,
	branch_no VARCHAR(50) NULL,
	inv_type TINYINT NULL,
	rep_name VARCHAR(40) NULL,
	up_date DATETIME NULL,
	hold char(1) NULL,
	override INT NULL,
	override2 INT NULL,
	override3 INT NULL,
	over_rate DECIMAL(7, 5) NULL,
	over2_rate DECIMAL(7, 5) NULL,
	over3_rate DECIMAL(7, 5) NULL,
	over_comm DECIMAL(10, 2) NULL,
	over2_comm DECIMAL(10, 2) NULL,
	over3_comm DECIMAL(10, 2) NULL,
	spl_rep2 INT NULL,
	spl_rep3 INT NULL,
	holdDate DATETIME NULL,
	holdNote VARCHAR(25) NULL,
	customerID INT NOT NULL,
	lastModifiedDate DATETIME NULL,
	spl_rep INT NULL,
	spl_rep4 INT NULL,
	spl_rep5 INT NULL,
	spl_amt DECIMAL(10, 2) NULL,
	spl_amt2 DECIMAL(10, 2) NULL,
	spl_amt3 DECIMAL(10, 2) NULL,
	spl_amt4 DECIMAL(10, 2) NULL,
	spl_amt5 DECIMAL(10, 2) NULL,
	spl_chg DECIMAL(7, 2) NULL,
	spl_chg2 DECIMAL(7, 2) NULL,
	spl_chg3 DECIMAL(7, 2) NULL,
	spl_chg4 DECIMAL(7, 2) NULL,
	spl_chg5 DECIMAL(7, 2) NULL,
	spl_comm DECIMAL(10, 2) NULL,
	spl2_comm DECIMAL(10, 2) NULL,
	spl3_comm DECIMAL(10, 2) NULL,
	spl4_comm DECIMAL(10, 2) NULL,
	spl5_comm DECIMAL(10, 2) NULL,
	clearing VARCHAR(20),
	cusip_no VARCHAR(9),
	rep_rate DECIMAL(7, 5),
	source VARCHAR(2),
  PRIMARY KEY (tradesID) 
);

CREATE TABLE `upclient` (
  `upclientID` int(11) NOT NULL AUTO_INCREMENT,
  `list_no` int(11) DEFAULT NULL,
  `list_group` varchar(10) DEFAULT NULL,
  `descript` varchar(30) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`upclientID`)
);

CREATE TABLE `upclienta` (
  `upclientaID` int(11) NOT NULL AUTO_INCREMENT,
  `fieldname` varchar(10) DEFAULT NULL,
  `list_group` varchar(10) DEFAULT NULL,
  `descript` varchar(30) DEFAULT NULL,
  `customerID` int(11) NOT NULL,
  `lastModifiedDate` datetime DEFAULT NULL,
  PRIMARY KEY (`upclientaID`)
);
